### ISSUE TITLE
发站内信没有生成相应message

### ISSUE THREAD

**Issue by bennyguo** [Ruaaaaaa/UnionInfoSystem#41]
发一个broadcast之后要给message表里面加东西呢！

**Comment by Colin97** [comment]
不是还没研究好怎么接受broadcast嘛

**Comment by bennyguo** [comment]
研究好了，发了一个broadcast之后，对于每一个需要接收这个广播的用户都要新建一条message，message表已经写好了，你看一下model的内容就知道了

**Comment by Colin97** [comment]
添加了，但是为啥我pull后会报这个错
FieldError: Cannot resolve keyword 'subunion' into field.
用户筛选也筛选不了了。

**Comment by bennyguo** [comment]
@Colin97 你应该需要删除数据库重来一遍？

**Comment by zfkuang** [comment]
生成啦
